# default Ruff config: https://docs.astral.sh/ruff/configuration/
# rules: https://docs.astral.sh/ruff/rules/

# line-length = 88
line-length = 130

extend-exclude = ["dissimilarity"]

[lint]
select = [
    "F",
    "E",
    "I",  # sort imports
    # "UP",
    "UP004",  # "class Foo(object)" not needed in Python 3
    "UP035",
    "FURB",
]

ignore = [
    # unused imports
    "F401",
    "E401",

    "E501", # line-too-long

    # UP rules:
    "UP031",
]


[lint.per-file-ignores]
"*.ipynb" = [
    "E402", # E402 	module-import-not-at-top-of-file
    "D",    # docstrings
]

[lint.pydocstyle]
# https://docs.astral.sh/ruff/settings/#lint_pydocstyle_convention
# convention = "TODO"
